Name: First workflow

on:
 push



jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: run 1 shell command
        runs: echo "Hello, World!"

      - name: run 2 shell commands
        runs: |
          echo "this is where i will run the second command"
          date
          pwd