name: "Test workflow"

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add this line to enable manual runs

# defining an env
env:
  MYWORKFLOW_ENV_VAR: "This is an workflow environment variable"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: run 1 shell command
        run: echo "Hello, World!"
      
      - name: run 2 shell commands
        run: |
          echo "this is where i will run the second command"
          date
          pwd
          echo "This is an environment variable from the workflow"
          echo ${{ env.MYWORKFLOW_ENV_VAR }}
